security:
    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_OAUTH_USER]

    providers:
        openriff_user_provider:
            id: openriff_security.user.provider.entity

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        app:
            pattern: ^/
            oauth:
                resource_owners:
                    soundcloud: /login/check-soundcloud
                login_path:   /login
                failure_path: /login
                oauth_user_provider:
                    service: openriff_security.user.provider.entity
            anonymous: true
            logout: true

        login:
            pattern:  ^/login$
            security: false
            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
