# https://github.com/KnpLabs/geekweek12/wiki/Routing

logout:
    pattern: /logout
    defaults: { _controller: App:Security:logout }

homepage:
    pattern: /
    defaults: { _controller: FrameworkBundle:Template:template, template: 'App::homepage.html.twig' }
